
task :default do
  sh 'rake --tasks'
end

#####

inputs = Dir.glob('**/*.erb')
outputs = inputs.map{|o| o[0..-5]}

require 'erb'
require 'open-uri'
require 'lib/attr_builder'

inputs.zip(outputs).each{ |input, output|
  file output => input do
    open output, 'w' do |o|
      $__class__ = (output.gsub %r{.*/}, '')[0..-5]
      o << ERB.new(open(input).read).result
    end
  end
}

desc 'erb preprocessing'
task :preprocess => [:begin, outputs, :end].flatten
task :begin do; puts "processing templates: #{inputs.inspect}"; end
task :end do; puts "processed output: #{outputs.inspect}"; end

#####

desc 'start building'
task :build => :preprocess do
  sh 'cmake .'
  sh 'make'
end
