
task :default do
  Rake.application.options.show_task_pattern = /./
  Rake.application.display_tasks_and_comments
end

#####

require 'rubygems'
gem 'ludy', '>=0.1.7'
require 'ludy/tasks/preprocess_cpp'
Project.name = 'cubeat'

#####

require 'rake/clean'
require 'fileutils'
CLEAN.include '*.o'
task :clobber => :clean do
  sh 'make clean' rescue nil
  File.delete 'Makefile' rescue nil
  File.delete 'CMakeCache.txt' rescue nil
  File.delete 'cmake_install.cmake' rescue nil
  FileUtils.rm_r 'CMakeFiles' rescue nil
end

#####

file :Makefile do
  sh 'cmake .'
end

desc 'preprocess and build'
task :build => [:prepare, :Makefile] do
  sh 'make'
end

desc 'clobber and build'
task :rebuild => [:clobber, :build]

desc 'prepare for build, doing custom preprocessing'
task :prepare => [:preprocess,
                  :reprocess_CMakeLists]

task :reprocess_CMakeLists do
  File.delete 'CMakeLists.txt'
  sh 'rake CMakeLists.txt'
end

#####

B = 'bundle'

desc "create mac's CuBeat.app"
task 'build:mac' => [:build, "#{B}/CuBeat.app"]

def mac_setup_binary binary, install_path="#{B}/CuBeat.app/Contents/MacOS"
  `otool -L #{binary}`.split("\n").select{ |path|
    next false unless path.start_with?("\t")
    path !~ %r{\t(/System/|/usr/lib/)}
  }.map{ |s| s[%r{(/\S+)+}] }.each{ |lib|
    name = File.basename(lib)
    dest = "#{install_path}/#{name}"
    sh "cp #{lib} #{dest}" unless File.exist?(dest)
    sh "chmod 644 #{dest}"
    sh "install_name_tool -change #{lib} '@loader_path/#{name}' #{binary}"
  }
end

file "#{B}/CuBeat.app" => ["#{B}/CuBeat.app/Contents/MacOS",
                           "#{B}/CuBeat.app/Contents/Resources"] do
  mac_setup_binary("#{B}/CuBeat.app/Contents/MacOS/CuBeat")
  mac_setup_binary("#{B}/CuBeat.app/Contents/MacOS/libcubeat.dylib")
  sh "cd #{B}; tar -zcf CuBeat.app.tgz CuBeat.app"
end

file "#{B}/CuBeat.app/Contents/MacOS" =>
                                    ['bin/cubeat',
                                     "#{B}/CuBeat.app/Contents/Resources"] do
  sh "mkdir -p #{B}/CuBeat.app/Contents/MacOS"
  sh "cp bin/cubeat #{B}/CuBeat.app/Contents/MacOS/CuBeat"
  sh "cp bin/libcubeat.dylib #{B}/CuBeat.app/Contents/Resources/"
end

file "#{B}/CuBeat.app/Contents/Resources" => ['bin/libcubeat.dylib'] do
  sh "mkdir -p #{B}/CuBeat.app/Contents/Resources"
  sh "cp -r rc #{B}/CuBeat.app/Contents/Resources/"
end

#####

desc 'build for linux'
task 'build:linux' => [:build,
                       "#{B}/CuBeat/bin",
                       "#{B}/CuBeat/lib",
                       "#{B}/CuBeat/rc"] do
  libs = %w[luajit alure boost_thread]
  linux_setup_binary(libs, "bin/cubeat")
  linux_setup_binary(libs, "bin/libcubeat.so")
  sh "cd #{B}; tar -zcf CuBeat.tgz CuBeat"
end

file "#{B}/CuBeat/bin" => ['bin/cubeat'] do
  sh "mkdir -p #{B}/CuBeat/bin"
  sh "cp bin/cubeat #{B}/CuBeat/bin/CuBeat"
end

file "#{B}/CuBeat/lib" => ['bin/libcubeat.so'] do
  sh "mkdir -p #{B}/CuBeat/lib"
  sh "cp bin/libcubeat.so #{B}/CuBeat/lib/"
  sh "chmod 644 #{B}/CuBeat/lib/libcubeat.so"
end

file "#{B}/CuBeat/rc" do
  sh "cp -r rc #{B}/CuBeat/rc"
end

def grep_path str
  str[/\[.+\]/][1..-2]
end

def linux_setup_binary wants, binary
  wants_regexp = Regexp.new(wants.join('|'))
  rpath = grep_path(`readelf -d #{binary} | grep RPATH`).split(':') +
          %w[/usr/lib /usr/local/lib]

  `readelf -d #{binary} | grep NEEDED`.split("\n").map{ |str|
    grep_path(str) }.select{ |lib| lib =~ wants_regexp }.each{ |name|
      prefix = rpath.find{ |path| File.exist?("#{path}/#{name}") }
      dest = "#{B}/CuBeat/lib/#{name}"
      if !File.exist?(dest)
        sh "cp #{prefix}/#{name} #{dest}"
        sh "chrpath -d #{dest}"
      end
      sh "chmod 644 #{dest}"
    }
end
